version: 1.0.{build}

image:
  - Visual Studio 2015

clone_depth: 1

notifications:
- provider: Email
  to:
  - robertsteckroth@gmail.com
  subject: A Bracket print build has failed.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9

install:
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: false

